version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directories:
      - "/.github/workflows"
      - "/.github/actions/**/*"
    schedule:
      interval: weekly
