name: PyToDa Github Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    name: Code quality
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/run-precommit

  tests:
    name: Run tests and coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/run-tests

  create_coverage_badge:
    name: Create coverage badge and comment
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Create coverage badge
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store coverage badge and comment in separate branch
        uses: actions/upload-artifact@v4.6.2
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt

  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - uses: ./.github/actions/build-docs

  deploy_docs:
    name: Deploy documentation
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: documentation
